### ISSUE TITLE
프론트엔드 CI 구축

### ISSUE THREAD

**Issue by hojunin** [sundayTen/pokr-web#17]
- [ ] sundayTen/pokr-server#19
- [ ] github apps를 활용한 리포팅
- [x] Docker bulid & Deploy 용량 최적화 (zero-install, 아티팩트 크기 줄이기)
- [x] pull request & issue template 만들기
- [x] 정적 분석 도구 세팅 (tsc, lint & lint-stage, prettier)
- [ ] sundayTen/pokr-web#20
- [x] sundayTen/pokr-server#48
